name: Build and Release HttpClient Curl Visualizer

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]  # Sadece "published" release'lerde tetikle

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Build adımları (öncekiyle aynı)
      - name: Upload Installation Package
        uses: actions/upload-artifact@v4
        with:
          name: Installation-Package
          path: installation-package/

  release:
    needs: build  # Build job'ının bitmesini bekle
    runs-on: windows-latest
    permissions:
      contents: write  # Release asset yüklemek için izin
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Installation-Package
          path: release-files/

      - name: Create ZIP
        run: |
          cd release-files
          Compress-Archive -Path * -DestinationPath HttpClientCurlVisualizer-${{ github.event.release.tag_name }}.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-files/HttpClientCurlVisualizer-${{ github.event.release.tag_name }}.zip
          asset_name: HttpClientCurlVisualizer-${{ github.event.release.tag_name }}.zip
