name: Build and Release HttpClient Curl Visualizer

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Restore NuGet packages
      run: nuget restore HttpClientCurlVisualizer.sln
      
    - name: Build Solution (Debug)
      run: msbuild HttpClientCurlVisualizer.sln /p:Configuration=Debug /p:Platform="Any CPU"
      
    - name: Build Solution (Release)
      run: msbuild HttpClientCurlVisualizer.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Upload Debug Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HttpClientCurlVisualizer-Debug
        path: |
          **/bin/Debug/**/*.dll
          **/bin/Debug/**/*.pdb
          
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HttpClientCurlVisualizer-Release
        path: |
          **/bin/Release/**/*.dll
          **/bin/Release/**/*.pdb
          
    - name: Create Installation Package
      run: |
        mkdir installation-package
        copy "HttpClientCurlVisualizer\bin\Release\HttpClientCurlVisualizer.dll" "installation-package\"
        copy "README.md" "installation-package\" 2>nul || echo "README not found"
        copy "INSTALL.md" "installation-package\" 2>nul || echo "INSTALL not found"
        
    - name: Upload Installation Package
      uses: actions/upload-artifact@v4
      with:
        name: Installation-Package
        path: installation-package/

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    if: github.event_name == 'release' && github.event.action == 'published' # Ek kontroller
    
    steps:
      - name: Debug Release Info
        run: |
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Upload URL: ${{ github.event.release.upload_url }}"
          echo "Event: ${{ toJson(github.event) }}"
          
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Installation-Package
          path: release-files/

      - name: Verify Files
        run: |
          cd release-files
          dir
          
      - name: Create ZIP
        run: |
          cd release-files
          $tag = "${{ github.event.release.tag_name }}"
          if (-not $tag) { $tag = "latest" }
          Compress-Archive -Path * -DestinationPath "HttpClientCurlVisualizer-$tag.zip"
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1 # Resmi GitHub eylemi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-files/HttpClientCurlVisualizer-${{ github.event.release.tag_name }}.zip
          asset_name: HttpClientCurlVisualizer-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
